export const PROVIDER_ADD_PROVIDER = 'PROVIDER_ADD_PROVIDER';
export const PROVIDER_CONNECTION_STATUS_BEGIN = 'PROVIDER_CONNECTION_STATUS_BEGIN';
export const PROVIDER_CONNECTION_STATUS_SUCCESS = 'PROVIDER_CONNECTION_STATUS_SUCCESS';
export const PROVIDER_CONNECTION_STATUS_FAILURE = 'PROVIDER_CONNECTION_STATUS_FAILURE';
export const PROVIDER_CONNECTION_STATUS_DISMISS_ERROR = 'PROVIDER_CONNECTION_STATUS_DISMISS_ERROR';
