export const ACCOUNTS_GET_ACCOUNTS_PROVIDER_BEGIN = 'ACCOUNTS_GET_ACCOUNTS_PROVIDER_BEGIN';
export const ACCOUNTS_GET_ACCOUNTS_PROVIDER_SUCCESS = 'ACCOUNTS_GET_ACCOUNTS_PROVIDER_SUCCESS';
export const ACCOUNTS_GET_ACCOUNTS_PROVIDER_FAILURE = 'ACCOUNTS_GET_ACCOUNTS_PROVIDER_FAILURE';
export const ACCOUNTS_GET_ACCOUNTS_PROVIDER_DISMISS_ERROR = 'ACCOUNTS_GET_ACCOUNTS_PROVIDER_DISMISS_ERROR';
export const ACCOUNTS_GET_BALANCE_BEGIN = 'ACCOUNTS_GET_BALANCE_BEGIN';
export const ACCOUNTS_GET_BALANCE_SUCCESS = 'ACCOUNTS_GET_BALANCE_SUCCESS';
export const ACCOUNTS_GET_BALANCE_FAILURE = 'ACCOUNTS_GET_BALANCE_FAILURE';
export const ACCOUNTS_GET_BALANCE_DISMISS_ERROR = 'ACCOUNTS_GET_BALANCE_DISMISS_ERROR';
